cloud:
  aws:
    credentials:
      access-key: AKIAVUITSRUTOMRKE2UW
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: petprojectimagestorage


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
